# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shorturl_pb2 as shorturl__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shorturl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShortUrlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateShortUrl = channel.unary_unary(
                '/ShortUrlService/CreateShortUrl',
                request_serializer=shorturl__pb2.CreateShortUrlRequest.SerializeToString,
                response_deserializer=shorturl__pb2.CreateShortUrlResponse.FromString,
                _registered_method=True)
        self.GetShortUrl = channel.unary_unary(
                '/ShortUrlService/GetShortUrl',
                request_serializer=shorturl__pb2.GetShortUrlRequest.SerializeToString,
                response_deserializer=shorturl__pb2.GetShortUrlResponse.FromString,
                _registered_method=True)
        self.ListShortUrls = channel.unary_unary(
                '/ShortUrlService/ListShortUrls',
                request_serializer=shorturl__pb2.ListShortUrlsRequest.SerializeToString,
                response_deserializer=shorturl__pb2.ListShortUrlsResponse.FromString,
                _registered_method=True)


class ShortUrlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateShortUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShortUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListShortUrls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShortUrlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateShortUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShortUrl,
                    request_deserializer=shorturl__pb2.CreateShortUrlRequest.FromString,
                    response_serializer=shorturl__pb2.CreateShortUrlResponse.SerializeToString,
            ),
            'GetShortUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShortUrl,
                    request_deserializer=shorturl__pb2.GetShortUrlRequest.FromString,
                    response_serializer=shorturl__pb2.GetShortUrlResponse.SerializeToString,
            ),
            'ListShortUrls': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShortUrls,
                    request_deserializer=shorturl__pb2.ListShortUrlsRequest.FromString,
                    response_serializer=shorturl__pb2.ListShortUrlsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ShortUrlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ShortUrlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShortUrlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateShortUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ShortUrlService/CreateShortUrl',
            shorturl__pb2.CreateShortUrlRequest.SerializeToString,
            shorturl__pb2.CreateShortUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShortUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ShortUrlService/GetShortUrl',
            shorturl__pb2.GetShortUrlRequest.SerializeToString,
            shorturl__pb2.GetShortUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListShortUrls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ShortUrlService/ListShortUrls',
            shorturl__pb2.ListShortUrlsRequest.SerializeToString,
            shorturl__pb2.ListShortUrlsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
