# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shorturl.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'shorturl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshorturl.proto\")\n\x0b\x46otoMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x62\x61se64\x18\x02 \x01(\t\"w\n\x0eUsuarioMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x15\n\radministrador\x18\x04 \x01(\x08\x12\x1a\n\x04\x66oto\x18\x05 \x01(\x0b\x32\x0c.FotoMessage\"\xa0\x01\n\x0fShortUrlMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0boriginalUrl\x18\x02 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x03 \x01(\t\x12\x12\n\nvisitCount\x18\x04 \x01(\x05\x12 \n\x07\x63reador\x18\x05 \x01(\x0b\x32\x0f.UsuarioMessage\x12\x14\n\x0cqrCodeBase64\x18\x06 \x01(\t\x12\x11\n\tsessionId\x18\x07 \x01(\t\"N\n\x15\x43reateShortUrlRequest\x12\x13\n\x0boriginalUrl\x18\x01 \x01(\t\x12 \n\x07\x63reador\x18\x02 \x01(\x0b\x32\x0f.UsuarioMessage\"<\n\x16\x43reateShortUrlResponse\x12\"\n\x08shortUrl\x18\x01 \x01(\x0b\x32\x10.ShortUrlMessage\" \n\x12GetShortUrlRequest\x12\n\n\x02id\x18\x01 \x01(\t\"9\n\x13GetShortUrlResponse\x12\"\n\x08shortUrl\x18\x01 \x01(\x0b\x32\x10.ShortUrlMessage\"\x16\n\x14ListShortUrlsRequest\"<\n\x15ListShortUrlsResponse\x12#\n\tshortUrls\x18\x01 \x03(\x0b\x32\x10.ShortUrlMessage2\xce\x01\n\x0fShortUrlService\x12\x41\n\x0e\x43reateShortUrl\x12\x16.CreateShortUrlRequest\x1a\x17.CreateShortUrlResponse\x12\x38\n\x0bGetShortUrl\x12\x13.GetShortUrlRequest\x1a\x14.GetShortUrlResponse\x12>\n\rListShortUrls\x12\x15.ListShortUrlsRequest\x1a\x16.ListShortUrlsResponseB\x1a\n\x08\x61pp.grpcB\x0cServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shorturl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\010app.grpcB\014ServiceProtoP\001'
  _globals['_FOTOMESSAGE']._serialized_start=18
  _globals['_FOTOMESSAGE']._serialized_end=59
  _globals['_USUARIOMESSAGE']._serialized_start=61
  _globals['_USUARIOMESSAGE']._serialized_end=180
  _globals['_SHORTURLMESSAGE']._serialized_start=183
  _globals['_SHORTURLMESSAGE']._serialized_end=343
  _globals['_CREATESHORTURLREQUEST']._serialized_start=345
  _globals['_CREATESHORTURLREQUEST']._serialized_end=423
  _globals['_CREATESHORTURLRESPONSE']._serialized_start=425
  _globals['_CREATESHORTURLRESPONSE']._serialized_end=485
  _globals['_GETSHORTURLREQUEST']._serialized_start=487
  _globals['_GETSHORTURLREQUEST']._serialized_end=519
  _globals['_GETSHORTURLRESPONSE']._serialized_start=521
  _globals['_GETSHORTURLRESPONSE']._serialized_end=578
  _globals['_LISTSHORTURLSREQUEST']._serialized_start=580
  _globals['_LISTSHORTURLSREQUEST']._serialized_end=602
  _globals['_LISTSHORTURLSRESPONSE']._serialized_start=604
  _globals['_LISTSHORTURLSRESPONSE']._serialized_end=664
  _globals['_SHORTURLSERVICE']._serialized_start=667
  _globals['_SHORTURLSERVICE']._serialized_end=873
# @@protoc_insertion_point(module_scope)
